# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8bef79074da238f6d845462786251751ea97e00a11e657061e80a7108a206857762887aa29cbe34a03d714981adb29babb850e16a0af8d45ee281522d4688c1

test:
  secret_key_base: c8fdd1eb298cac7575da6a8bf1726c6c8b3a338f47ae3ef3851395b36cc3c9214b90bdcb4d4e368def2991cef16a6934deafe0d3bca92cea1cc51ce21c0279a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
